-- CreateTable
CREATE TABLE "QRCode" (
    "id" SERIAL NOT NULL,
    "type" VARCHAR(255) NOT NULL,
    "petId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "QRCode" ADD FOREIGN KEY ("petId") REFERENCES "Pet"("id") ON DELETE CASCADE ON UPDATE CASCADE;
